### ISSUE TITLE
var OR let option for swift class variables!

### ISSUE THREAD

**Issue by Mushrankhan** [jsonmaster/jsonmaster.github.io#21]
**Is your feature request related to a problem? Please describe.**
- If user needs var, then we need to replace all "let" keywords to "var", manually.

**Describe the solution you'd like**
- You can give radio button option for "let" OR "var".

**Comment by mukeshydv** [comment]
Done!

**Comment by Mushrankhan** [comment]
Thanks a lot for the instant enhancement.

Great to see that you has taken the suggestions and implemented quickly.

Hope this lib will grow more and more, and in future if you need any help feel free to contact me! Happy to help. 😄  👍
