### ISSUE TITLE
Optionals in Swift Codeable

### ISSUE THREAD

**Issue by ashish1405** [jsonmaster/jsonmaster.github.io#22]
**Is your feature request related to a problem? Please describe.**
There is a way in swift to create optional variables in codeable. This is helpful when the json-object and object-json conversion has some missing variables.

**Describe the solution you'd like**
I've done some changes by forking the repo, but I'm not sure how to write for different optional types. In my code I've defaulted to string. Please see my diff image below. I can make a pull request but as this is incomplete, can't do it.

**Describe alternatives you've considered**
Don't know any

**Additional context**
<img width="1638" alt="Screenshot 2021-06-25 at 10 05 26 PM" src="https://user-images.githubusercontent.com/1269220/123457790-eaf26e80-d601-11eb-8469-1f1fc637fd4d.png">

**Comment by pavankalyanjonnadula** [comment]
May i know the above issue got resolved?

I facing this problem. Any solution.

By using codable i need to get optional properties . Any other way help me

**Comment by mukeshydv** [comment]
Optional support is added for Swift and Kotlin.
